# Generated by Django 6.0 on 2026-01-28 14:04

import apps.backend.retention.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retention', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tenantretentionstatus',
            new_name='retention_t_status_9c22bc_idx',
            old_name='retention_t_status_idx',
        ),
        migrations.AlterField(
            model_name='globalretentionpolicy',
            name='allowed_actions_during_grace',
            field=models.JSONField(default=apps.backend.retention.models._default_allowed_actions),
        ),
    ]
