from django.urls import path

from . import api_views

urlpatterns = [
    path("overview", api_views.overview, name="saas_admin_overview"),
    path("observability/summary", api_views.observability_summary, name="saas_admin_observability_summary"),
    path("ai-chatbot/usage/summary", api_views.ai_chatbot_usage_summary, name="saas_admin_ai_chatbot_usage_summary"),
    path("ai-chatbot/usage/trend", api_views.ai_chatbot_usage_trend, name="saas_admin_ai_chatbot_usage_trend"),
    path("ai-chatbot/openai/settings", api_views.ai_chatbot_openai_settings, name="saas_admin_ai_chatbot_openai_settings"),
    path("ai-chatbot/openai/test", api_views.ai_chatbot_openai_test, name="saas_admin_ai_chatbot_openai_test"),
    path("settings/retention-policy", api_views.retention_policy_settings, name="saas_admin_retention_policy"),
    path("settings/media-storage", api_views.media_storage_settings, name="saas_admin_media_storage_settings"),
    path("settings/media-storage/pull-local/preview", api_views.media_storage_pull_preview, name="saas_admin_media_storage_pull_preview"),
    path("settings/media-storage/pull-local/start", api_views.media_storage_pull_start, name="saas_admin_media_storage_pull_start"),
    path("settings/media-storage/pull-local/status/<uuid:job_id>", api_views.media_storage_pull_status, name="saas_admin_media_storage_pull_status"),
    path("settings/storage-sync", api_views.storage_sync_settings, name="saas_admin_storage_sync_settings"),
    path("settings/backup-retention", api_views.backup_retention_settings, name="saas_admin_backup_retention_settings"),
    path("settings/backup-retention/org/<int:org_id>", api_views.org_backup_retention_override, name="saas_admin_backup_retention_org"),
    path("settings/backup-retention/product/<int:product_id>", api_views.product_backup_retention_override, name="saas_admin_backup_retention_product"),
    path("backup-activity", api_views.backup_activity, name="saas_admin_backup_activity"),
    path("storage/usage", api_views.storage_usage_summary, name="saas_admin_storage_usage"),
    path("storage/product", api_views.storage_product_upsert, name="saas_admin_storage_product_upsert"),
    path("storage/plan", api_views.storage_plan_upsert, name="saas_admin_storage_plan_upsert"),
    path("storage/addon", api_views.storage_addon_upsert, name="saas_admin_storage_addon_upsert"),
    path("storage/assign-plan", api_views.storage_assign_plan, name="saas_admin_storage_assign_plan"),
    path("storage/org-addon", api_views.storage_org_addon_quantity, name="saas_admin_storage_org_addon"),
    path("storage/usage/rebuild", api_views.storage_usage_rebuild, name="saas_admin_storage_usage_rebuild"),
    path("products/<slug:slug>", api_views.product_detail, name="saas_admin_product_detail"),
    path("organizations", api_views.organizations_list, name="saas_admin_orgs"),
    path("organizations/<int:org_id>", api_views.organization_detail, name="saas_admin_org_detail"),
    path("deleted-accounts/<int:account_id>", api_views.deleted_account_detail, name="saas_admin_deleted_account_detail"),
    path("inbox", api_views.inbox_list, name="saas_admin_inbox"),
    path("inbox/read", api_views.inbox_mark_read, name="saas_admin_inbox_read"),
    path("inbox/<int:notification_id>", api_views.inbox_delete, name="saas_admin_inbox_delete"),
    path("dealers/<int:dealer_id>", api_views.dealer_detail, name="saas_admin_dealer_detail"),
    path("plans", api_views.plans_list, name="saas_admin_plans"),
    path("plans/<int:plan_id>", api_views.plan_detail, name="saas_admin_plan_detail"),
    path("products/<slug:slug>/organizations", api_views.product_organizations, name="saas_admin_product_orgs"),
    path("products/<slug:slug>/users", api_views.product_users, name="saas_admin_product_users"),
    path("products/<slug:slug>/users/<int:user_id>", api_views.product_user_detail, name="saas_admin_product_user_detail"),
    path("products/<slug:slug>/pending-transfers", api_views.product_pending_transfers, name="saas_admin_product_pending"),
    path("products/<slug:slug>/pending-transfers/<int:transfer_id>", api_views.product_pending_transfer_detail, name="saas_admin_product_pending_detail"),
    path("products/<slug:slug>/pending-transfers/<int:transfer_id>/receipt-clear", api_views.product_pending_transfer_clear_receipt, name="saas_admin_product_pending_clear_receipt"),
    path("products/<slug:slug>/pending-transfers/<int:transfer_id>/<str:action>", api_views.product_pending_transfer_action, name="saas_admin_product_pending_action"),
    path("products/<slug:slug>/transfer-history", api_views.product_transfer_history, name="saas_admin_product_transfer_history"),
    path("products/<slug:slug>/billing-history", api_views.product_billing_history, name="saas_admin_product_billing_history"),
    path("billing-history", api_views.billing_history, name="saas_admin_billing_history"),
    path("billing-gst-archive", api_views.billing_gst_archive, name="saas_admin_billing_gst_archive"),
    path("products/<slug:slug>/renewals", api_views.product_renewals, name="saas_admin_product_renewals"),
    path("products/<slug:slug>/referrals", api_views.product_referrals, name="saas_admin_product_referrals"),
    path("products/<slug:slug>/support-access", api_views.product_support_access, name="saas_admin_product_support_access"),
    path("referrals", api_views.referrals_summary, name="saas_admin_referrals"),
    path("referrals/settings", api_views.referrals_update_settings, name="saas_admin_referrals_settings"),
    path("referrals/earnings/<int:earning_id>", api_views.referrals_update_payout, name="saas_admin_referrals_payout"),
    path("referrals/dealers/<int:dealer_id>", api_views.referrals_update_dealer, name="saas_admin_referrals_dealer"),
    path("referrals/dealer-earnings/<int:earning_id>", api_views.referrals_update_dealer_payout, name="saas_admin_referrals_dealer_payout"),
]
