# Generated by Django 6.0 on 2026-01-28 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_alter_chatwidget_public_chat_code'),
        ('saas_admin', '0004_openai_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgproductentitlement',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitor_org_product_entitlements', to='core.organization'),
        ),
    ]
