# Generated by Django 6.0 on 2026-01-28 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_alter_chatwidget_public_chat_code'),
        ('saas_admin', '0005_alter_orgproductentitlement_organization'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrgProductEntitlement',
            new_name='MonitorOrgProductEntitlement',
        ),
    ]
