from django.urls import path

from . import api_views

urlpatterns = [
    path("dashboard/summary", api_views.dashboard_summary, name="ai_chatbot_dashboard_summary"),
    path("widget/config", api_views.widget_config, name="ai_chatbot_widget_config"),
    path("widget/lead", api_views.widget_lead, name="ai_chatbot_widget_lead"),
    path("widget/message", api_views.widget_message, name="ai_chatbot_widget_message"),
    path("widget/attachment", api_views.widget_attachment, name="ai_chatbot_widget_attachment"),
    path("widget/thread", api_views.widget_thread, name="ai_chatbot_widget_thread"),
    path("enquiry", api_views.enquiry_submit, name="ai_chatbot_enquiry_submit"),
    path("leads", api_views.leads_list, name="ai_chatbot_leads_list"),
    path("leads/<int:lead_id>", api_views.lead_update, name="ai_chatbot_lead_update"),
    path("leads/<int:lead_id>/delete", api_views.lead_delete, name="ai_chatbot_lead_delete"),
    path("org/agents", api_views.org_agents, name="ai_chatbot_org_agents"),
    path("org/agents/<int:agent_id>", api_views.org_agent_detail, name="ai_chatbot_org_agent_detail"),
    path("org/agents/<int:agent_id>/password", api_views.org_agent_password, name="ai_chatbot_org_agent_password"),
    path("org/chat-settings", api_views.chat_settings, name="ai_chatbot_chat_settings"),
    path("widgets", api_views.widgets_collection, name="ai_chatbot_widgets_collection"),
    path("widgets/<int:widget_id>", api_views.widget_update, name="ai_chatbot_widget_update"),
    path("inbox/conversations", api_views.inbox_conversations, name="ai_chatbot_inbox_conversations"),
    path("inbox/conversations/<int:conversation_id>/messages", api_views.inbox_messages, name="ai_chatbot_inbox_messages"),
    path("inbox/conversations/<int:conversation_id>/reply", api_views.inbox_reply, name="ai_chatbot_inbox_reply"),
    path("inbox/conversations/<int:conversation_id>/attachment", api_views.inbox_attachment, name="ai_chatbot_inbox_attachment"),
    path("inbox/conversations/<int:conversation_id>/close", api_views.inbox_close, name="ai_chatbot_inbox_close"),
    path("inbox/conversations/<int:conversation_id>/reopen", api_views.inbox_reopen, name="ai_chatbot_inbox_reopen"),
    path("inbox/conversations/<int:conversation_id>/take", api_views.inbox_take_conversation, name="ai_chatbot_inbox_take_conversation"),
    path("inbox/conversations/<int:conversation_id>/transfer", api_views.inbox_transfer_conversation, name="ai_chatbot_inbox_transfer_conversation"),
    path("history", api_views.history_list, name="ai_chatbot_history_list"),
    path("history/<int:conversation_id>/messages", api_views.history_messages, name="ai_chatbot_history_messages"),
    path("history/<int:conversation_id>", api_views.history_delete, name="ai_chatbot_history_delete"),
    path("media-library", api_views.media_library_list, name="ai_chatbot_media_library_list"),
    path("media-library/website-import", api_views.media_library_website_import, name="ai_chatbot_media_library_website_import"),
    path("media-library/<int:item_id>/reupload", api_views.media_library_reupload, name="ai_chatbot_media_library_reupload"),
    path("media-library/delete", api_views.media_library_delete, name="ai_chatbot_media_library_delete"),
    path("faqs", api_views.faq_list, name="ai_chatbot_faq_list"),
    path("faqs/<int:faq_id>", api_views.faq_detail, name="ai_chatbot_faq_detail"),
]
