# Generated by Django 6.0 on 2026-01-10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enquiries", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enquiry",
            name="ip_address",
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AddField(
            model_name="enquiry",
            name="user_agent",
            field=models.TextField(blank=True),
        ),
    ]
