# Generated by Django 6.0 on 2026-01-10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteBrandSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("site_name", models.CharField(default="Work Zilla", max_length=120)),
                ("primary_color", models.CharField(default="#1f6f8b", max_length=20)),
                ("secondary_color", models.CharField(default="#0f172a", max_length=20)),
                ("accent_color", models.CharField(blank=True, max_length=20)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="brand/")),
                ("favicon", models.ImageField(blank=True, null=True, upload_to="brand/")),
                ("support_email", models.EmailField(blank=True, max_length=254)),
                ("support_phone", models.CharField(blank=True, max_length=30)),
                ("default_meta_title", models.CharField(blank=True, max_length=160)),
                ("default_meta_description", models.TextField(blank=True)),
                ("og_image", models.ImageField(blank=True, null=True, upload_to="brand/")),
            ],
            options={
                "verbose_name": "Site Brand Settings",
                "verbose_name_plural": "Site Brand Settings",
            },
        ),
    ]
