# Generated by Django 4.2.10 on 2026-01-29 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='backupauditlog',
            new_name='backups_bac_organiz_a3cb11_idx',
            old_name='backups_bac_organiz_9d644b_idx',
        ),
        migrations.RenameIndex(
            model_name='backupauditlog',
            new_name='backups_bac_action_12f803_idx',
            old_name='backups_bac_action_9b705b_idx',
        ),
        migrations.RenameIndex(
            model_name='backupauditlog',
            new_name='backups_bac_backup__67d469_idx',
            old_name='backups_bac_backup__e8d54e_idx',
        ),
        migrations.RenameIndex(
            model_name='backupauditlog',
            new_name='backups_bac_request_841a12_idx',
            old_name='backups_bac_request_12f2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='backuprecord',
            new_name='backups_bac_organiz_01312e_idx',
            old_name='backups_bac_organiz_184e52_idx',
        ),
        migrations.RenameIndex(
            model_name='backuprecord',
            new_name='backups_bac_status_449df9_idx',
            old_name='backups_bac_status_1a32f4_idx',
        ),
        migrations.RenameIndex(
            model_name='backuprecord',
            new_name='backups_bac_request_6f0f61_idx',
            old_name='backups_bac_request_9d1b89_idx',
        ),
    ]
