# Generated by Django 4.2.10 on 2026-02-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0002_rename_backups_bac_organiz_9d644b_idx_backups_bac_organiz_a3cb11_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureToggle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, unique=True)),
                ('route', models.CharField(max_length=255)),
                ('permission', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
