# Generated by Django 4.2.10 on 2026-03-28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backups", "0003_featuretoggle"),
        ("core", "0148_socialmediacompany_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrgGoogleDriveBackupSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True)),
                ("product_slug", models.CharField(default="business-autopilot-erp", max_length=120)),
                ("google_access_token", models.TextField(blank=True, default="")),
                ("google_refresh_token", models.TextField(blank=True, default="")),
                ("google_token_expiry", models.DateTimeField(blank=True, null=True)),
                ("google_drive_folder_id", models.CharField(blank=True, default="", max_length=255)),
                ("oauth_state", models.CharField(blank=True, default="", max_length=255)),
                ("oauth_state_created_at", models.DateTimeField(blank=True, null=True)),
                ("scheduler_enabled", models.BooleanField(default=False)),
                (
                    "schedule_frequency",
                    models.CharField(
                        choices=[("daily", "Daily"), ("weekly", "Weekly")],
                        default="daily",
                        max_length=16,
                    ),
                ),
                ("schedule_weekday", models.PositiveSmallIntegerField(default=0)),
                ("schedule_hour_utc", models.PositiveSmallIntegerField(default=2)),
                ("schedule_minute_utc", models.PositiveSmallIntegerField(default=0)),
                ("keep_last_backups", models.PositiveSmallIntegerField(default=7)),
                ("scheduler_last_run_at", models.DateTimeField(blank=True, null=True)),
                ("last_backup_status", models.CharField(blank=True, default="", max_length=32)),
                ("last_backup_at", models.DateTimeField(blank=True, null=True)),
                ("last_error_message", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="org_google_backup_settings",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Google Backup Settings",
                "verbose_name_plural": "Organization Google Backup Settings",
            },
        ),
    ]
