# Generated by Django 4.2.10 on 2026-02-24 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saas_admin', '0016_seed_whatsapp_automation_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemBackupManagerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='google_drive', max_length=40, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('google_client_id', models.CharField(blank=True, default='', max_length=255)),
                ('google_client_secret', models.TextField(blank=True, default='')),
                ('google_redirect_uri', models.URLField(blank=True, default='')),
                ('google_access_token', models.TextField(blank=True, default='')),
                ('google_refresh_token', models.TextField(blank=True, default='')),
                ('google_token_expiry', models.DateTimeField(blank=True, null=True)),
                ('google_drive_folder_id', models.CharField(blank=True, default='', max_length=255)),
                ('oauth_state', models.CharField(blank=True, default='', max_length=128)),
                ('oauth_state_created_at', models.DateTimeField(blank=True, null=True)),
                ('scheduler_enabled', models.BooleanField(default=False)),
                ('schedule_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=16)),
                ('schedule_weekday', models.PositiveSmallIntegerField(default=0)),
                ('schedule_hour_utc', models.PositiveSmallIntegerField(default=2)),
                ('schedule_minute_utc', models.PositiveSmallIntegerField(default=0)),
                ('scheduler_last_run_at', models.DateTimeField(blank=True, null=True)),
                ('keep_last_backups', models.PositiveSmallIntegerField(default=7)),
                ('last_error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Backup Manager Settings',
                'verbose_name_plural': 'System Backup Manager Settings',
            },
        ),
        migrations.CreateModel(
            name='SystemBackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('trigger', models.CharField(choices=[('manual', 'Manual'), ('scheduler', 'Scheduler')], default='manual', max_length=20)),
                ('message', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('temp_sql_path', models.TextField(blank=True, default='')),
                ('temp_zip_path', models.TextField(blank=True, default='')),
                ('sql_size_bytes', models.BigIntegerField(default=0)),
                ('zip_size_bytes', models.BigIntegerField(default=0)),
                ('drive_sql_file_id', models.CharField(blank=True, default='', max_length=255)),
                ('drive_sql_file_name', models.CharField(blank=True, default='', max_length=255)),
                ('drive_zip_file_id', models.CharField(blank=True, default='', max_length=255)),
                ('drive_zip_file_name', models.CharField(blank=True, default='', max_length=255)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_backup_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
