# Generated by Django 4.2.10 on 2026-02-24 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_fix_whatsapp_automation_addon_pricing_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saas_admin', '0017_systembackupmanagersettings_systembackuplog'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationRestoreLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('downloading', 'Downloading'), ('validating', 'Validating'), ('restoring', 'Restoring'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('backup_file_id', models.CharField(blank=True, default='', max_length=255)),
                ('backup_file_name', models.CharField(blank=True, default='', max_length=255)),
                ('temp_download_path', models.TextField(blank=True, default='')),
                ('temp_restore_db_path', models.TextField(blank=True, default='')),
                ('validation_summary', models.JSONField(blank=True, default=dict)),
                ('restored_records', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True, default='')),
                ('errors', models.TextField(blank=True, default='')),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saas_org_restore_logs', to='core.organization')),
                ('restored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_restore_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['organization', 'created_at'], name='saas_admin__organiz_6b166a_idx'), models.Index(fields=['status', 'created_at'], name='saas_admin__status_4802f6_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationBackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('trigger', models.CharField(choices=[('manual', 'Manual'), ('scheduler', 'Scheduler'), ('bulk_manual', 'Bulk Manual')], default='manual', max_length=20)),
                ('backup_scope', models.CharField(default='org_data', max_length=20)),
                ('temp_file_path', models.TextField(blank=True, default='')),
                ('temp_file_size_bytes', models.BigIntegerField(default=0)),
                ('drive_file_id', models.CharField(blank=True, default='', max_length=255)),
                ('drive_file_name', models.CharField(blank=True, default='', max_length=255)),
                ('drive_folder_path', models.CharField(blank=True, default='', max_length=255)),
                ('records_exported', models.IntegerField(default=0)),
                ('model_count', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saas_org_backup_logs', to='core.organization')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_backup_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['organization', 'created_at'], name='saas_admin__organiz_8403ec_idx'), models.Index(fields=['status', 'created_at'], name='saas_admin__status_c56e53_idx')],
            },
        ),
    ]
