# Generated by Django 4.2.10 on 2026-03-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saas_admin", "0018_organizationrestorelog_organizationbackuplog"),
    ]

    operations = [
        migrations.CreateModel(
            name="AmazonSESSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(default="amazon_ses", max_length=40, unique=True)),
                ("is_active", models.BooleanField(default=False)),
                ("aws_region", models.CharField(default="us-east-1", max_length=40)),
                ("access_key_id", models.CharField(blank=True, default="", max_length=128)),
                ("secret_access_key", models.TextField(blank=True, default="")),
                ("smtp_username", models.CharField(blank=True, default="", max_length=128)),
                ("smtp_password", models.TextField(blank=True, default="")),
                ("sender_email", models.EmailField(blank=True, default="", max_length=254)),
                ("sender_name", models.CharField(blank=True, default="", max_length=120)),
                ("reply_to_email", models.EmailField(blank=True, default="", max_length=254)),
                ("configuration_set", models.CharField(blank=True, default="", max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Amazon SES Settings",
                "verbose_name_plural": "Amazon SES Settings",
            },
        ),
    ]
