# Generated by Django 4.2.10 on 2026-03-28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saas_admin", "0022_force_product_sort_order_sequence"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlackblazeBackupSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(default="blackblaze", max_length=40, unique=True)),
                ("is_active", models.BooleanField(default=False)),
                ("db_enabled", models.BooleanField(default=True)),
                ("db_interval_hours", models.PositiveSmallIntegerField(default=4)),
                ("db_retention_days", models.PositiveSmallIntegerField(default=7)),
                ("script_enabled", models.BooleanField(default=True)),
                ("script_daily_hour_local", models.PositiveSmallIntegerField(default=21)),
                ("script_daily_minute_local", models.PositiveSmallIntegerField(default=0)),
                ("script_retention_days", models.PositiveSmallIntegerField(default=7)),
                ("last_db_backup_at", models.DateTimeField(blank=True, null=True)),
                ("last_script_backup_at", models.DateTimeField(blank=True, null=True)),
                ("last_error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Blackblaze Backup Settings",
                "verbose_name_plural": "Blackblaze Backup Settings",
            },
        ),
        migrations.CreateModel(
            name="BlackblazeBackupArtifact",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "backup_type",
                    models.CharField(
                        choices=[("db", "Database"), ("script", "SaaS Files")],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("running", "Running"), ("completed", "Completed"), ("failed", "Failed"), ("expired", "Expired")],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("storage_path", models.TextField(blank=True, default="")),
                ("file_name", models.CharField(blank=True, default="", max_length=255)),
                ("size_bytes", models.BigIntegerField(default=0)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="blackblazebackupartifact",
            index=models.Index(fields=["backup_type", "created_at"], name="bb_art_type_created_idx"),
        ),
        migrations.AddIndex(
            model_name="blackblazebackupartifact",
            index=models.Index(fields=["status", "created_at"], name="bb_art_status_created_idx"),
        ),
    ]
