# Generated by Django 4.2.10 on 2026-02-05 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='alertevent',
            new_name='monitoring__server__da1537_idx',
            old_name='monitoring_alert_server_type_idx',
        ),
        migrations.RenameIndex(
            model_name='alertevent',
            new_name='monitoring__started_12827e_idx',
            old_name='monitoring_alert_started_idx',
        ),
        migrations.RenameIndex(
            model_name='metricsample',
            new_name='monitoring__server__d01c3c_idx',
            old_name='monitoring_server_ts_idx',
        ),
    ]
