# Generated by Django 4.2.10 on 2026-02-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_autopilot', '0002_organizationuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationuser',
            name='employee_role',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
