# Generated by Django 4.2.10 on 2026-02-19 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_alter_chatwidget_public_chat_code'),
        ('business_autopilot', '0003_organizationuser_employee_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationEmployeeRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_autopilot_employee_roles', to='core.organization')),
            ],
            options={
                'ordering': ('name',),
                'unique_together': {('organization', 'name')},
            },
        ),
    ]
