# Generated by Django 4.2.10 on 2026-03-14 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0129_organization_country_organization_currency'),
        ('business_autopilot', '0007_org_department_and_user_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSalaryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=160)),
                ('source_user_id', models.PositiveIntegerField(blank=True, null=True)),
                ('effective_from', models.DateField()),
                ('increment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_autopilot_salary_history', to='core.organization')),
            ],
            options={
                'ordering': ('-effective_from', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hra', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('conveyance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('special_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_allowances', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('apply_pf', models.BooleanField(default=True)),
                ('apply_esi', models.BooleanField(default=True)),
                ('professional_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_autopilot_salary_structures', to='core.organization')),
            ],
            options={
                'ordering': ('name', 'id'),
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PayrollSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_pf', models.BooleanField(default=True)),
                ('enable_esi', models.BooleanField(default=True)),
                ('pf_employee_percent', models.DecimalField(decimal_places=2, default=12, max_digits=5)),
                ('pf_employer_percent', models.DecimalField(decimal_places=2, default=12, max_digits=5)),
                ('esi_employee_percent', models.DecimalField(decimal_places=2, default=0.75, max_digits=5)),
                ('esi_employer_percent', models.DecimalField(decimal_places=2, default=3.25, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_autopilot_payroll_settings', to='core.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_autopilot_payroll_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='PayrollEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=160)),
                ('source_user_id', models.PositiveIntegerField(blank=True, null=True)),
                ('payroll_month', models.CharField(max_length=7)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('gross_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pf_employee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pf_employer_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('esi_employee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('esi_employer_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('professional_tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_deduction_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('earnings', models.JSONField(blank=True, default=dict)),
                ('deductions', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processed', 'Processed'), ('paid', 'Paid')], default='processed', max_length=20)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_autopilot_payroll_entries', to='core.organization')),
                ('salary_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_entries', to='business_autopilot.employeesalaryhistory')),
                ('salary_structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_entries', to='business_autopilot.salarystructure')),
            ],
            options={
                'ordering': ('-payroll_month', 'employee_name', '-id'),
            },
        ),
        migrations.AddField(
            model_name='employeesalaryhistory',
            name='salary_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_history_entries', to='business_autopilot.salarystructure'),
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slip_number', models.CharField(max_length=80)),
                ('generated_for_month', models.CharField(max_length=7)),
                ('employee_name', models.CharField(max_length=160)),
                ('source_user_id', models.PositiveIntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_autopilot_payslips', to='core.organization')),
                ('payroll_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payslip', to='business_autopilot.payrollentry')),
            ],
            options={
                'ordering': ('-generated_at', '-id'),
                'unique_together': {('organization', 'slip_number')},
            },
        ),
    ]
