# Generated by Django 4.2.10 on 2026-03-14 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_autopilot', '0008_employeesalaryhistory_salarystructure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalaryhistory',
            name='monthly_salary_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='auto_special_allowance',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='basic_salary_percent',
            field=models.DecimalField(decimal_places=2, default=40, max_digits=5),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='conveyance_fixed',
            field=models.DecimalField(decimal_places=2, default=1600, max_digits=12),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='hra_percent',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
