# Generated by Django 4.2.10 on 2026-03-14 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_autopilot', '0009_employeesalaryhistory_monthly_salary_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalaryhistory',
            name='current_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeesalaryhistory',
            name='increment_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='employeesalaryhistory',
            name='increment_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeesalaryhistory',
            name='new_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
