# Generated by Django 4.2.10 on 2026-03-17 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("business_autopilot", "0010_employeesalaryhistory_current_salary_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=160)),
                ("description", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_autopilot_subscription_categories",
                        to="core.organization",
                    ),
                ),
            ],
            options={"ordering": ("name",), "unique_together": {("organization", "name")}},
        ),
        migrations.CreateModel(
            name="SubscriptionSubCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=160)),
                ("description", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_autopilot_subscription_sub_categories",
                        to="core.organization",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_sub_categories",
                        to="business_autopilot.subscriptioncategory",
                    ),
                ),
            ],
            options={"ordering": ("category_id", "name"), "unique_together": {("organization", "category", "name")}},
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subscription_title", models.CharField(max_length=255)),
                ("customer_id", models.BigIntegerField(blank=True, null=True)),
                ("payment_description", models.TextField(blank=True, default="")),
                ("amount", models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ("currency", models.CharField(default="INR", max_length=10)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("next_billing_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(choices=[("Active", "Active"), ("Expired", "Expired"), ("Cancelled", "Cancelled")], default="Active", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subscriptions",
                        to="business_autopilot.subscriptioncategory",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="business_autopilot_created_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_autopilot_subscriptions",
                        to="core.organization",
                    ),
                ),
                (
                    "sub_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subscriptions",
                        to="business_autopilot.subscriptionsubcategory",
                    ),
                ),
            ],
            options={"ordering": ("-created_at",)},
        ),
    ]
