# Generated by Django 4.2.10 on 2026-03-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business_autopilot", "0011_subscriptions_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="plan_duration_days",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
