# Generated by Django 4.2.10 on 2026-03-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business_autopilot", "0013_subscription_alert_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="email_alert_days",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="whatsapp_alert_days",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
