# Generated by Django 4.2.10 on 2026-03-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business_autopilot", "0014_subscription_alert_days_to_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="email_alert_assign_to",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="whatsapp_alert_assign_to",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
