# Generated by Django 4.2.10 on 2026-03-31 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0149_normalize_business_autopilot_plan_product'),
        ('business_autopilot', '0016_crmlead_crmdeal_crmsalesorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrmMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('company_or_client_name', models.CharField(blank=True, default='', max_length=180)),
                ('related_to', models.CharField(blank=True, default='', max_length=180)),
                ('meeting_date', models.DateField(blank=True, null=True)),
                ('meeting_time', models.TimeField(blank=True, null=True)),
                ('owner_names', models.TextField(blank=True, default='')),
                ('owner_user_ids', models.JSONField(blank=True, default=list)),
                ('meeting_mode', models.CharField(blank=True, default='', max_length=30)),
                ('reminder_channels', models.JSONField(blank=True, default=list)),
                ('reminder_days', models.JSONField(blank=True, default=list)),
                ('reminder_minutes', models.JSONField(blank=True, default=list)),
                ('reminder_summary', models.CharField(blank=True, default='', max_length=255)),
                ('reminder_email_sent_map', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Rescheduled', 'Rescheduled'), ('Cancelled', 'Cancelled'), ('Missed', 'Missed')], default='Scheduled', max_length=30)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_autopilot_crm_created_meetings', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_autopilot_crm_deleted_meetings', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_autopilot_crm_meetings', to='core.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_autopilot_crm_updated_meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
