# Generated by Django 4.2.10 on 2026-04-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_autopilot', '0017_crmmeeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationuser',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
