# Generated by Django 4.2.10 on 2026-04-03 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0149_normalize_business_autopilot_plan_product'),
        ('business_autopilot', '0018_organizationuser_deleted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrmContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('company', models.CharField(blank=True, default='', max_length=180)),
                ('email', models.CharField(blank=True, default='', max_length=180)),
                ('phone_country_code', models.CharField(blank=True, default='+91', max_length=10)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('tag', models.CharField(choices=[('Client', 'Client'), ('Prospect', 'Prospect'), ('Vendor', 'Vendor')], default='Client', max_length=30)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_autopilot_crm_created_contacts', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_autopilot_crm_deleted_contacts', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_autopilot_crm_contacts', to='core.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_autopilot_crm_updated_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
