# Generated by Django 4.2.10 on 2026-05-05 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_autopilot', '0027_crmlead_final_proposal_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='crmleadproposaldocument',
            new_name='business_au_organiz_92797a_idx',
            old_name='business_aut_organiz_2b7ee1_idx',
        ),
        migrations.AlterField(
            model_name='crmlead',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Onhold', 'Onhold'), ('Closed', 'Closed'), ('Converted', 'Converted')], default='Open', max_length=30),
        ),
    ]
