# Generated by Django 4.2.10 on 2026-05-15 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business_autopilot', '0028_rename_business_aut_organiz_2b7ee1_idx_business_au_organiz_92797a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmlead',
            name='completed_by_team',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='crmlead',
            name='completed_by_type',
            field=models.CharField(blank=True, choices=[('Users', 'Users'), ('Team', 'Team')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='crmlead',
            name='completed_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_autopilot_crm_completed_leads', to=settings.AUTH_USER_MODEL),
        ),
    ]
