# Generated by Django 4.2.10 on 2026-05-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_autopilot', '0029_crmlead_completed_by_team_crmlead_completed_by_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmlead',
            name='completed_by_user_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='crmlead',
            name='completed_by_team_names',
            field=models.JSONField(blank=True, default=list),
        ),
    ]

