# Generated by Django 4.2.10 on 2026-05-22 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0151_subscription_scheduled_plan'),
        ('business_autopilot', '0030_crmlead_completed_by_user_ids_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrmLeadModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_reference_id', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('lead_name', models.CharField(blank=True, default='', max_length=180)),
                ('action', models.CharField(choices=[('create', 'create'), ('update', 'update'), ('delete', 'delete'), ('delete_permanent', 'delete_permanent'), ('restore', 'restore')], default='update', max_length=40)),
                ('changes', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_autopilot_crm_lead_modifications', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifications', to='business_autopilot.crmlead')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_autopilot_crm_lead_modifications', to='core.organization')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['organization', 'lead', 'created_at'], name='business_au_organiz_7a80ee_idx'), models.Index(fields=['organization', 'lead_reference_id', 'created_at'], name='business_au_organiz_5596ae_idx')],
            },
        ),
    ]
