# Generated by Django 4.2.10 on 2026-05-27 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business_autopilot', '0031_crmleadmodification'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationuser',
            name='resigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='resigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_autopilot_resigned_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('resigned', 'Resigned'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
