# Generated by Django 4.2.10 on 2026-05-28 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_autopilot', '0032_organizationuser_resigned_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationuser',
            name='user_type',
            field=models.CharField(choices=[('crm_user', 'CRM User'), ('hrm_user', 'HRM User'), ('full_access_user', 'Full Access User')], db_index=True, default='full_access_user', max_length=32),
        ),
    ]
