# Generated by Django 4.2.10 on 2026-06-13 12:45

import apps.backend.business_autopilot.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0156_rename_core_busine_organiz_7bc690_idx_core_busine_organiz_57f367_idx_and_more'),
        ('business_autopilot', '0034_attendance_geo_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceentry',
            name='admin_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='attendanceentry',
            name='attendance_mode',
            field=models.CharField(choices=[('internal', 'Internal'), ('external', 'External'), ('admin', 'Admin'), ('self', 'Self')], default='self', max_length=16),
        ),
        migrations.AddField(
            model_name='attendanceentry',
            name='external_verification_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='attendanceentry',
            name='face_match_score',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='attendanceentry',
            name='face_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendanceentry',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendanceentry',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_autopilot_attendance_verified_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='face_enrolled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FaceRecognitionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('require_internal_face', models.BooleanField(default=False)),
                ('require_external_face', models.BooleanField(default=False)),
                ('min_match_score', models.DecimalField(decimal_places=2, default=0.9, max_digits=4)),
                ('photo_retention_days', models.PositiveIntegerField(default=60)),
                ('allow_external_photo_proof', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_autopilot_face_recognition_setting', to='core.organization')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='EmployeeFaceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_embedding', models.TextField()),
                ('embedding_model_name', models.CharField(default='face_recognition/128d', max_length=120)),
                ('enrolled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_profile', to='business_autopilot.organizationuser')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_autopilot_employee_face_profiles', to='core.organization')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='AttendancePhotoProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.backend.business_autopilot.models._attendance_photo_proof_upload_to)),
                ('attendance_mode', models.CharField(choices=[('internal', 'Internal'), ('external', 'External'), ('admin', 'Admin'), ('self', 'Self')], default='self', max_length=16)),
                ('face_verified', models.BooleanField(default=False)),
                ('face_match_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('gps_accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('location_status', models.CharField(blank=True, default='', max_length=64)),
                ('external_verification_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_proofs', to='business_autopilot.attendanceentry')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_photo_proofs', to='business_autopilot.organizationuser')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_autopilot_attendance_photo_proofs', to='core.organization')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_autopilot_attendance_verified_proofs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
