# Generated by Django 4.2.10 on 2026-06-15 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0156_rename_core_busine_organiz_7bc690_idx_core_busine_organiz_57f367_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business_autopilot', '0035_attendanceentry_admin_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(blank=True, default='', max_length=64)),
                ('estimate_sequence', models.PositiveIntegerField()),
                ('estimate_number', models.CharField(max_length=32)),
                ('mobile', models.CharField(db_index=True, max_length=30)),
                ('client_name', models.CharField(max_length=180)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.TextField(blank=True, default='')),
                ('gst_number', models.CharField(blank=True, default='', max_length=32)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('created', 'Created'), ('shared', 'Shared'), ('cancelled', 'Cancelled')], default='created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_autopilot_quick_estimates_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_autopilot_quick_estimates', to='core.organization')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='QuickEstimateSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_autopilot_quick_estimate_sequence', to='core.organization')),
            ],
            options={
                'ordering': ('organization_id',),
            },
        ),
        migrations.CreateModel(
            name='QuickEstimateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(blank=True, default='', max_length=180)),
                ('description', models.TextField(blank=True, default='')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unit', models.CharField(blank=True, default='', max_length=40)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quick_estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='business_autopilot.quickestimate')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='SiteAdminChatState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.CharField(blank=True, choices=[('quick_estimate', 'Quick Estimate')], default='', max_length=40)),
                ('current_step', models.CharField(blank=True, default='', max_length=40)),
                ('collected_data', models.JSONField(blank=True, default=dict)),
                ('awaiting_whatsapp_share', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_quick_estimate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_admin_chat_states', to='business_autopilot.quickestimate')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_autopilot_site_admin_states', to='core.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_autopilot_site_admin_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
                'indexes': [models.Index(fields=['organization', 'user', 'updated_at'], name='business_au_organiz_0d6a28_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='siteadminchatstate',
            constraint=models.UniqueConstraint(fields=('organization', 'user'), name='uniq_ba_site_admin_state_org_user'),
        ),
        migrations.AddIndex(
            model_name='quickestimate',
            index=models.Index(fields=['organization', 'mobile'], name='business_au_organiz_6aa30d_idx'),
        ),
        migrations.AddIndex(
            model_name='quickestimate',
            index=models.Index(fields=['organization', 'status', 'created_at'], name='business_au_organiz_4eae97_idx'),
        ),
        migrations.AddConstraint(
            model_name='quickestimate',
            constraint=models.UniqueConstraint(fields=('organization', 'estimate_sequence'), name='uniq_ba_quick_estimate_org_sequence'),
        ),
        migrations.AddConstraint(
            model_name='quickestimate',
            constraint=models.UniqueConstraint(fields=('organization', 'estimate_number'), name='uniq_ba_quick_estimate_org_number'),
        ),
    ]
