# Generated by Django 4.2.10 on 2026-06-19 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_autopilot', '0039_quickestimate_progress_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickestimatehistory',
            name='action',
            field=models.CharField(choices=[('updated', 'Updated'), ('assigned', 'Assigned'), ('unassigned', 'Unassigned'), ('cancelled', 'Cancelled'), ('reopened', 'Reopened')], default='updated', max_length=24),
        ),
    ]
