"""
Django settings for emp_monitor project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

def _csv_env(name, default=""):
    raw = os.environ.get(name, default).strip()
    if not raw:
        return []
    return [item.strip() for item in raw.split(",") if item.strip()]


def _bool_env(name, default="0"):
    return os.environ.get(name, default) == "1"

ENVIRONMENT = os.environ.get("ENVIRONMENT", "local").strip().lower()


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "django-insecure-change-me")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "1") == "1"

if ENVIRONMENT == "production":
    ALLOWED_HOSTS = ["getworkzilla.com", "www.getworkzilla.com"]
else:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1", "0.0.0.0"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'oauth2_provider',
    'dashboard',
    'core.apps.CoreConfig',
    'saas_admin',
    #'payments',
]

CORS_ALLOWED_ORIGINS = _csv_env("DJANGO_CORS_ALLOWED_ORIGINS")
CSRF_TRUSTED_ORIGINS = _csv_env("DJANGO_CSRF_TRUSTED_ORIGINS")
CORS_ALLOW_CREDENTIALS = _bool_env("DJANGO_CORS_ALLOW_CREDENTIALS", "1")
CORS_ALLOW_ALL_ORIGINS = _bool_env("DJANGO_CORS_ALLOW_ALL_ORIGINS", "0")

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
LOGOUT_REDIRECT_URL = '/accounts/login/'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'dashboard.middleware.LoginSessionGuardMiddleware',
    'dashboard.middleware.HrReadOnlyMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'dashboard.middleware.OrganizationRequiredMiddleware',
]

ROOT_URLCONF = 'emp_monitor.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'dashboard' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request',
                'dashboard.context_processors.subscription_context',
                'dashboard.context_processors.theme_context',
                'dashboard.context_processors.site_nav_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'emp_monitor.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'frontend' / 'app' / 'dist',
    BASE_DIR / 'dashboard' / 'static',
]
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/accounts/login/'
X_FRAME_OPTIONS = "SAMEORIGIN"

OAUTH2_PROVIDER = {
    "ACCESS_TOKEN_EXPIRE_SECONDS": 3600,
    "REFRESH_TOKEN_EXPIRE_SECONDS": 1209600,
    "SCOPES": {
        "read": "Read access",
        "write": "Write access",
    },
}

# ==========================
# Invoice / GST Defaults
# ==========================
INVOICE_SELLER = {
    "name": "Work Zilla Monitor",
    "address_line1": "51/1, Justice Ramaswamy Street",
    "address_line2": "Kamaraj Ave 2nd St, Adyar",
    "city": "Chennai",
    "state": "Tamil Nadu",
    "postal_code": "600020",
    "country": "India",
    "gstin": "33AAQVP1234A1Z7",
    "sac": "997331",
    "support_email": "billing@workzilla.in",
}
INVOICE_SELLER_STATE_CODE = "33"
INVOICE_TAX_RATE = 18
INVOICE_NUMBER_PREFIX = "WZ"

# ==========================
# Renewal Window (days)
# ==========================
RENEW_WINDOW_DAYS_MONTHLY = 7
RENEW_WINDOW_DAYS_YEARLY = 15

# ==========================
# Razorpay Test Credentials
# ==========================
RAZORPAY_KEY_ID = "rzp_test_1234567890ABCDE"
RAZORPAY_KEY_SECRET = "1234567890abcdef1234567890"

# Keep legacy AutoField to avoid unexpected BigAutoField migrations.
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True
SECURE_SSL_REDIRECT = _bool_env("DJANGO_SECURE_SSL_REDIRECT", "0")
CSRF_COOKIE_SECURE = _bool_env("DJANGO_CSRF_COOKIE_SECURE", "0")
SESSION_COOKIE_SECURE = _bool_env("DJANGO_SESSION_COOKIE_SECURE", "0")
