# Generated by Django 4.2.10 on 2026-02-27 09:12

import apps.backend.imposition.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0114_organizationsettings_sidebar_menu_style_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpositionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('business', 'Business'), ('enterprise', 'Enterprise')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('device_limit', models.PositiveIntegerField(default=1)),
                ('additional_user_price_monthly_inr', models.DecimalField(decimal_places=2, default=300, max_digits=10)),
                ('feature_flags', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ImpositionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('template_type', models.CharField(choices=[('id_card', 'ID Card'), ('business_card', 'Business Card')], max_length=30)),
                ('layout', models.JSONField(blank=True, default=dict)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_imposition_templates', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imposition_templates', to='core.organization')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ImpositionOrgSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('trialing', 'Trialing'), ('inactive', 'Inactive'), ('expired', 'Expired')], default='active', max_length=20)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imposition_subscriptions', to='core.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='org_subscriptions', to='imposition.impositionplan')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='ImpositionOrgAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addon_code', models.CharField(choices=[('additional_user', 'Additional User')], default='additional_user', max_length=40)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('unit_price_monthly_inr', models.DecimalField(decimal_places=2, default=300, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imposition_addons', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ImpositionLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=apps.backend.imposition.models._generate_license_code, max_length=40, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='active', max_length=20)),
                ('offline_grace_days', models.PositiveSmallIntegerField(default=3)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imposition_licenses', to='core.organization')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licenses', to='imposition.impositionorgsubscription')),
            ],
        ),
        migrations.CreateModel(
            name='ImpositionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('id_card', 'ID Card'), ('business_card', 'Business Card')], max_length=30)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('sheet_size', models.CharField(default='A4', max_length=40)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('output_meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imposition_jobs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imposition_jobs', to='core.organization')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='ImpositionDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=120)),
                ('device_name', models.CharField(blank=True, default='', max_length=200)),
                ('os', models.CharField(blank=True, default='', max_length=80)),
                ('app_version', models.CharField(blank=True, default='', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('last_active_at', models.DateTimeField(auto_now=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='imposition.impositionlicense')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imposition_devices', to='core.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imposition_devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImpositionDataImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_type', models.CharField(choices=[('id_card', 'ID Card'), ('business_card', 'Business Card')], max_length=30)),
                ('source_filename', models.CharField(blank=True, default='', max_length=255)),
                ('mapping', models.JSONField(blank=True, default=dict)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processed', 'Processed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imposition_imports', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imposition_imports', to='core.organization')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ImpositionUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=60)),
                ('event_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to='imposition.impositiondevice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imposition_usage_logs', to='core.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imposition_usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['organization', 'event_type'], name='imposition_log_org_event_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='impositionorgsubscription',
            index=models.Index(fields=['organization', 'status'], name='imposition_sub_org_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='impositionorgaddon',
            unique_together={('organization', 'addon_code')},
        ),
        migrations.AddIndex(
            model_name='impositionlicense',
            index=models.Index(fields=['organization', 'status'], name='imposition_lic_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='impositionjob',
            index=models.Index(fields=['organization', 'status'], name='imposition_job_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='impositiondevice',
            index=models.Index(fields=['organization', 'is_active'], name='imposition_dev_org_active_idx'),
        ),
        migrations.AddIndex(
            model_name='impositiondevice',
            index=models.Index(fields=['license', 'is_active'], name='imposition_dev_lic_active_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='impositiondevice',
            unique_together={('organization', 'device_id')},
        ),
    ]
