# Generated by Django 4.2.10 on 2026-03-06 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imposition', '0005_imposition_addon_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impositionaddoncatalog',
            name='product',
            field=models.CharField(default='Print Marks', max_length=120),
        ),
    ]
