# Generated by Django 6.0 on 2026-01-01 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_organization_settings_privacy_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingtransfer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='addon_usd_monthly_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Addon USD monthly price'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='addon_usd_yearly_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Addon USD yearly price'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='retention_days',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='plan',
            name='screenshot_min_minutes',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 minute'), (2, '2 minutes'), (3, '3 minutes'), (5, '5 minutes'), (10, '10 minutes'), (15, '15 minutes'), (20, '20 minutes'), (30, '30 minutes')], default=5),
        ),
        migrations.AlterField(
            model_name='plan',
            name='usd_monthly_price',
            field=models.FloatField(blank=True, null=True, verbose_name='USD monthly price'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='usd_yearly_price',
            field=models.FloatField(blank=True, null=True, verbose_name='USD yearly price'),
        ),
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
