# Generated by Django 6.0 on 2026-01-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_billingprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address_line1', models.CharField(blank=True, max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(blank=True, max_length=120)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='India', max_length=60)),
                ('gstin', models.CharField(blank=True, max_length=20)),
                ('sac', models.CharField(default='997331', max_length=20)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('state_code', models.CharField(blank=True, max_length=4)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
