# Generated by Django 6.0 on 2026-01-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_invoicesellerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesellerprofile',
            name='bank_account_details',
            field=models.TextField(blank=True),
        ),
    ]
