# Generated by Django 6.0 on 2026-01-19 13:15

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_chat_enquiry_lead_status'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aiusageevent',
            new_name='core_aiusag_organiz_19a702_idx',
            old_name='core_aiusag_organize_94b9a6_idx',
        ),
        migrations.RenameIndex(
            model_name='aiusageevent',
            new_name='core_aiusag_organiz_7e9ada_idx',
            old_name='core_aiusag_organize_3d7d2a_idx',
        ),
        migrations.RenameIndex(
            model_name='aiusagemonthly',
            new_name='core_aiusag_period__ff17ab_idx',
            old_name='core_aiusag_period__94c4b7_idx',
        ),
        migrations.RenameIndex(
            model_name='aiusagemonthly',
            new_name='core_aiusag_organiz_7da75e_idx',
            old_name='core_aiusag_organiz_9b9a32_idx',
        ),
        migrations.RenameIndex(
            model_name='chatconversation',
            new_name='core_chatco_widget__bd1c62_idx',
            old_name='core_chatco_widget__29c25d_idx',
        ),
        migrations.RenameIndex(
            model_name='chatenquirylead',
            new_name='core_chaten_organiz_e84818_idx',
            old_name='core_chaten_organize_7e3e43_idx',
        ),
        migrations.RenameIndex(
            model_name='chatenquirylead',
            new_name='core_chaten_widget__78afd6_idx',
            old_name='core_chaten_widget__5f5a76_idx',
        ),
        migrations.RenameIndex(
            model_name='chatlead',
            new_name='core_chatle_organiz_7e7433_idx',
            old_name='core_chatle_organiz_6fd6f7_idx',
        ),
        migrations.RenameIndex(
            model_name='chatlead',
            new_name='core_chatle_widget__3aa4f1_idx',
            old_name='core_chatle_widget__f94e0e_idx',
        ),
        migrations.RenameIndex(
            model_name='eventmetric',
            new_name='core_eventm_date_9bd6db_idx',
            old_name='core_eventm_date_9f1515_idx',
        ),
        migrations.RenameIndex(
            model_name='eventmetric',
            new_name='core_eventm_organiz_cd645c_idx',
            old_name='core_eventm_organiza_996b53_idx',
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chatwidget',
            name='public_chat_code',
            field=models.CharField(default=core.models._generate_chat_code, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='eventmetric',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('company_admin', 'Company Admin'), ('hr_view', 'HR View'), ('ai_chatbot_agent', 'AI Chatbot Agent'), ('dealer', 'Dealer')], default='company_admin', max_length=20),
        ),
    ]
