# Generated by Django 6.0 on 2026-01-25 05:14

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_alter_chatwidget_public_chat_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiMediaLibraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('pdf', 'PDF'), ('word', 'Word'), ('text', 'Text'), ('word_website_data', 'Website Data'), ('extra_text', 'Extra Text')], max_length=30)),
                ('source_url', models.URLField(blank=True, max_length=500, null=True)),
                ('file_path', models.FileField(blank=True, null=True, upload_to=core.models._ai_media_library_upload_to)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_media_library_items', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'created_at'], name='core_aimedi_organiz_779c1e_idx')],
            },
        ),
    ]
