# Generated by Django 6.0 on 2026-01-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_alter_chatwidget_public_chat_code_aimedialibraryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimedialibraryitem',
            name='text_content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
