# Generated by Django 6.0 on 2026-01-25 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_aimedialibraryitem_text_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiFaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'created_at'], name='core_aifaq_organiz_2d4d8b_idx')],
            },
        ),
    ]
