# Generated by Django 6.0 on 2026-01-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_plan_ai_library_limit_mb'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimedialibraryitem',
            name='is_auto_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aimedialibraryitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
