# Generated by Django 4.2.10 on 2026-02-05

from django.conf import settings
from django.db import migrations, models
import uuid


def backfill_device_limits(apps, schema_editor):
    Plan = apps.get_model("core", "Plan")
    for plan in Plan.objects.all():
        name = (plan.name or "").strip().lower()
        if "basic" in name:
            limit = 2
        elif "standard" in name:
            limit = 3
        elif "pro" in name:
            limit = 5
        elif "trial" in name or "free" in name:
            limit = 1
        else:
            limit = 1
        if plan.device_limit != limit:
            plan.device_limit = limit
            plan.save(update_fields=["device_limit"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0096_add_storage_bandwidth_limits"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="device_limit",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                ("device_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("device_name", models.CharField(blank=True, default="", max_length=200)),
                ("os_info", models.CharField(blank=True, default="", max_length=200)),
                ("app_version", models.CharField(blank=True, default="", max_length=50)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("org", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="devices", to="core.organization")),
                ("user", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="devices", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["org", "user", "is_active"], name="core_device_org_use_b0db7b_idx"),
                    models.Index(fields=["user", "last_seen"], name="core_device_user_id_8d02b4_idx"),
                ],
            },
        ),
        migrations.RunPython(backfill_device_limits, migrations.RunPython.noop),
    ]
