# Generated by ChatGPT on 2026-02-08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0099_monitor_stop_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminNotification",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField(blank=True)),
                ("event_type", models.CharField(choices=[("org_expired", "Org Account Expired"), ("org_renewed", "Org Account Renewed"), ("org_created", "New Account Created"), ("payment_pending", "Pending Payment"), ("payment_success", "Payment Success"), ("payment_failed", "Payment Failed"), ("product_activation", "Product Activation"), ("system", "System Notification")], default="system", max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("organization", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.organization")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
