# Generated by Django 4.2.10 on 2026-02-13 03:55

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_adminnotification'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='monitorstopevent',
            new_name='core_monito_employe_72bcb7_idx',
            old_name='core_monito_employee_0f0a2f_idx',
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chatwidget',
            name='public_chat_code',
            field=models.CharField(default=core.models._generate_chat_code, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='monitorstopevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
