# Generated by Django 4.2.10 on 2026-02-13 14:15

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_rename_core_monito_employee_0f0a2f_idx_core_monito_employe_72bcb7_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatwidget',
            name='public_chat_code',
            field=models.CharField(default=core.models._generate_chat_code, max_length=32, unique=True),
        ),
    ]
