# Generated by Django 4.2.10 on 2026-02-19 11:20

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_add_business_autopilot_free_trial_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatwidget',
            name='public_chat_code',
            field=models.CharField(default=core.models._generate_chat_code, max_length=32, unique=True),
        ),
    ]
