# Generated by Django 4.2.10 on 2026-02-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_alter_chatwidget_public_chat_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='theme_primary_color',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='theme_secondary_color',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
