# Generated by Django 4.2.10 on 2026-02-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0112_organizationsettings_theme_primary_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminactivity',
            name='product_slug',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
