# Generated by Django 4.2.10 on 2026-02-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_adminactivity_product_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='sidebar_menu_style',
            field=models.CharField(blank=True, default='default', max_length=32),
        ),
    ]
