# Generated by Django 4.2.10 on 2026-03-05 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0119_alter_chatwidget_public_chat_code'),
        ('core', '0122_enable_whatsapp_free_trial_full_features'),
    ]

    operations = [
    ]
