# Generated by Django 4.2.10 on 2026-03-05 06:54

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0123_merge_20260305_0530'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgSupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_slug', models.CharField(blank=True, default='', max_length=120)),
                ('category', models.CharField(choices=[('support', 'Support'), ('sales', 'Sales')], default='support', max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('last_message_at', models.DateTimeField(auto_now_add=True)),
                ('last_read_by_org_at', models.DateTimeField(blank=True, null=True)),
                ('last_read_by_saas_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OrgSupportTicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=core.models._org_ticket_attachment_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrgSupportTicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_role', models.CharField(choices=[('org_admin', 'Org Admin'), ('saas_admin', 'SaaS Admin'), ('system', 'System')], default='org_admin', max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='orgsupportticketmessage',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orgsupportticketmessage',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.orgsupportticket'),
        ),
        migrations.AddField(
            model_name='orgsupportticketattachment',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.orgsupportticketmessage'),
        ),
        migrations.AddField(
            model_name='orgsupportticketattachment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.orgsupportticket'),
        ),
        migrations.AddField(
            model_name='orgsupportticketattachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orgsupportticket',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_support_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orgsupportticket',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='core.organization'),
        ),
        migrations.AddIndex(
            model_name='orgsupportticketmessage',
            index=models.Index(fields=['ticket', 'created_at'], name='core_orgsup_ticket__23c8c3_idx'),
        ),
        migrations.AddIndex(
            model_name='orgsupportticketmessage',
            index=models.Index(fields=['author_role', 'created_at'], name='core_orgsup_author__15bb24_idx'),
        ),
        migrations.AddIndex(
            model_name='orgsupportticketattachment',
            index=models.Index(fields=['ticket', 'created_at'], name='core_orgsup_ticket__a5f626_idx'),
        ),
        migrations.AddIndex(
            model_name='orgsupportticket',
            index=models.Index(fields=['organization', 'status'], name='core_orgsup_organiz_c58698_idx'),
        ),
        migrations.AddIndex(
            model_name='orgsupportticket',
            index=models.Index(fields=['organization', 'product_slug'], name='core_orgsup_organiz_7488f1_idx'),
        ),
        migrations.AddIndex(
            model_name='orgsupportticket',
            index=models.Index(fields=['category', 'status'], name='core_orgsup_categor_498a07_idx'),
        ),
    ]
