# Generated by Django 4.2.10 on 2026-03-06 04:05

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0125_themesettings_public_server_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='organizationproduct',
            new_name='org_product_organiz_70d807_idx',
            old_name='org_product_org_status_idx',
        ),
        migrations.RenameIndex(
            model_name='organizationproduct',
            new_name='org_product_product_ab6cef_idx',
            old_name='org_product_prod_status_idx',
        ),
        migrations.RenameIndex(
            model_name='userproductaccess',
            new_name='user_produc_user_id_aa988c_idx',
            old_name='user_product_access_user_perm_idx',
        ),
        migrations.RenameIndex(
            model_name='userproductaccess',
            new_name='user_produc_product_4472b2_idx',
            old_name='user_product_access_prod_perm_idx',
        ),
        migrations.AlterField(
            model_name='chatwidget',
            name='public_chat_code',
            field=models.CharField(default=core.models._generate_chat_code, max_length=32, unique=True),
        ),
    ]
