# Generated by Django 4.2.10 on 2026-03-14 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0128_organization_soft_delete_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='country',
            field=models.CharField(default='India', max_length=60),
        ),
        migrations.AddField(
            model_name='organization',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
    ]
