# Generated by Django 4.2.10 on 2026-03-14 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0129_organization_country_organization_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
