# Generated by Django 4.2.10 on 2026-03-16 07:56

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0133_userprofile_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnotification',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_admin_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='AdminNotificationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=core.models._org_inbox_attachment_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.adminnotification')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['notification', 'created_at'], name='core_adminn_notific_49a01b_idx')],
            },
        ),
    ]
