# Generated by Django 4.2.10 on 2026-03-21 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0134_organizationsettings_session_timeout_and_user_login_activity'),
        ('core', '0141_update_digital_automation_free_trial_limits'),
    ]

    operations = [
    ]
