# Generated by Django 4.2.10 on 2026-03-21 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0142_merge_20260321_0746'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userloginactivity',
            new_name='core_userlo_organiz_ef4b36_idx',
            old_name='core_userlo_organiz_810661_idx',
        ),
        migrations.RenameIndex(
            model_name='userloginactivity',
            new_name='core_userlo_user_id_428c35_idx',
            old_name='core_userlo_user_id_5c66ce_idx',
        ),
    ]
