# Generated by Django 4.2.10 on 2026-03-26 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0144_organizationsettings_business_autopilot_role_access_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPlatformConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('x', 'X'), ('linkedin', 'LinkedIn')], max_length=20)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('error', 'Error')], default='disconnected', max_length=20)),
                ('is_connected', models.BooleanField(default=False)),
                ('account_id', models.CharField(blank=True, default='', max_length=200)),
                ('api_base_url', models.URLField(blank=True, default='', max_length=500)),
                ('api_endpoint', models.URLField(blank=True, default='', max_length=700)),
                ('access_token', models.TextField(blank=True, default='')),
                ('refresh_token', models.TextField(blank=True, default='')),
                ('token_type', models.CharField(blank=True, default='Bearer', max_length=40)),
                ('scopes', models.TextField(blank=True, default='')),
                ('extra_headers', models.JSONField(blank=True, default=dict)),
                ('last_connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_platform_connections', to='core.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_social_platform_connections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialPostJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('media_url', models.URLField(blank=True, default='', max_length=1000)),
                ('target_platforms', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('processing', 'Processing'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('publish_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('result_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_post_jobs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_post_jobs', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='SocialPostDispatchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('x', 'X'), ('linkedin', 'LinkedIn')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('http_status', models.PositiveIntegerField(blank=True, null=True)),
                ('external_post_id', models.CharField(blank=True, default='', max_length=255)),
                ('response_body', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_logs', to='core.socialplatformconnection')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_post_dispatch_logs', to='core.organization')),
                ('post_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_logs', to='core.socialpostjob')),
            ],
        ),
        migrations.AddIndex(
            model_name='socialpostjob',
            index=models.Index(fields=['organization', 'status'], name='core_social_organiz_69386d_idx'),
        ),
        migrations.AddIndex(
            model_name='socialpostjob',
            index=models.Index(fields=['organization', 'scheduled_at'], name='core_social_organiz_8866fa_idx'),
        ),
        migrations.AddIndex(
            model_name='socialpostjob',
            index=models.Index(fields=['organization', 'created_at'], name='core_social_organiz_0f7a2f_idx'),
        ),
        migrations.AddIndex(
            model_name='socialpostdispatchlog',
            index=models.Index(fields=['organization', 'platform', 'attempted_at'], name='core_social_organiz_90c81b_idx'),
        ),
        migrations.AddIndex(
            model_name='socialpostdispatchlog',
            index=models.Index(fields=['post_job', 'platform'], name='core_social_post_jo_4761df_idx'),
        ),
        migrations.AddIndex(
            model_name='socialplatformconnection',
            index=models.Index(fields=['organization', 'platform'], name='core_social_organiz_2245d9_idx'),
        ),
        migrations.AddIndex(
            model_name='socialplatformconnection',
            index=models.Index(fields=['organization', 'is_connected'], name='core_social_organiz_fd920c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='socialplatformconnection',
            unique_together={('organization', 'platform')},
        ),
    ]
