# Generated by Django 4.2.10 on 2026-03-26 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0147_set_company_count_for_digital_automation_trial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='socialplatformconnection',
            name='core_social_organiz_2245d9_idx',
        ),
        migrations.AddField(
            model_name='socialmediacompany',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_social_media_companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='socialmediacompany',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_companies', to='core.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='socialplatformconnection',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='socialplatformconnection',
            name='social_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platform_connections', to='core.socialmediacompany'),
        ),
        migrations.AddField(
            model_name='socialpostjob',
            name='social_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_jobs', to='core.socialmediacompany'),
        ),
        migrations.AlterUniqueTogether(
            name='socialplatformconnection',
            unique_together={('organization', 'social_company', 'platform')},
        ),
        migrations.AddIndex(
            model_name='socialplatformconnection',
            index=models.Index(fields=['organization', 'social_company', 'platform'], name='core_social_organiz_242996_idx'),
        ),
        migrations.AddIndex(
            model_name='socialpostjob',
            index=models.Index(fields=['organization', 'social_company', 'status'], name='core_social_organiz_4974ea_idx'),
        ),
        migrations.AddIndex(
            model_name='socialmediacompany',
            index=models.Index(fields=['organization', 'is_active'], name='core_social_organiz_b95ca3_idx'),
        ),
        migrations.AddIndex(
            model_name='socialmediacompany',
            index=models.Index(fields=['organization', 'name'], name='core_social_organiz_45b6f5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='socialmediacompany',
            unique_together={('organization', 'name')},
        ),
    ]
