# Generated by Django 4.2.10 on 2026-05-28 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0151_subscription_scheduled_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='business_autopilot_user_type_access_map',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pendingtransfer',
            name='user_type_counts',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='subscription',
            name='user_type_counts',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='subscription',
            name='user_type_next_cycle_counts',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='subscriptionhistory',
            name='user_type_counts',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
