# Generated by Django 4.2.10 on 2026-06-12 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0155_businessautopilotchathistory'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='businessautopilotchathistory',
            new_name='core_busine_organiz_57f367_idx',
            old_name='core_busine_organiz_7bc690_idx',
        ),
        migrations.RenameIndex(
            model_name='businessautopilotchathistory',
            new_name='core_busine_organiz_e75a86_idx',
            old_name='core_busine_organiz_dafcdc_idx',
        ),
    ]
