# Generated by Django 4.2.10 on 2026-02-23 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_automation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappsettings',
            name='company_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_settings', to='whatsapp_automation.companyprofile'),
        ),
        migrations.CreateModel(
            name='DigitalCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_slug', models.SlugField(max_length=220, unique=True)),
                ('theme_color', models.CharField(blank=True, default='#22c55e', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digital_card', to='whatsapp_automation.companyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CataloguePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_slug', models.SlugField(max_length=220, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='catalogue_page', to='whatsapp_automation.companyprofile')),
            ],
        ),
    ]
