# Generated by Django 4.2.10 on 2026-02-24 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_automation', '0002_whatsappsettings_company_profile_digitalcard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cataloguepage',
            name='about_content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cataloguepage',
            name='about_title',
            field=models.CharField(blank=True, default='About Us', max_length=120),
        ),
        migrations.AddField(
            model_name='cataloguepage',
            name='contact_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cataloguepage',
            name='contact_title',
            field=models.CharField(blank=True, default='Contact', max_length=120),
        ),
        migrations.AddField(
            model_name='cataloguepage',
            name='services_content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cataloguepage',
            name='services_title',
            field=models.CharField(blank=True, default='Services', max_length=120),
        ),
    ]
