# Generated by Django 4.2.10 on 2026-02-24 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_fix_whatsapp_automation_addon_pricing_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('whatsapp_automation', '0003_cataloguepage_about_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalCardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_slug', models.SlugField(max_length=220, unique=True)),
                ('card_title', models.CharField(blank=True, default='', max_length=200)),
                ('person_name', models.CharField(blank=True, default='', max_length=200)),
                ('role_title', models.CharField(blank=True, default='', max_length=200)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('whatsapp_number', models.CharField(blank=True, default='', max_length=40)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('website', models.URLField(blank=True, default='')),
                ('address', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('theme_color', models.CharField(blank=True, default='#22c55e', max_length=20)),
                ('logo_image_data', models.TextField(blank=True, default='')),
                ('hero_banner_image_data', models.TextField(blank=True, default='')),
                ('logo_size', models.PositiveSmallIntegerField(default=96)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='digital_card_entries', to='whatsapp_automation.companyprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wa_digital_card_entries_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wa_digital_card_entries', to='core.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wa_digital_card_entries_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
