# Generated by Django 4.2.10 on 2026-02-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_automation', '0004_digitalcardentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalcardentry',
            name='custom_domain',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='digitalcardentry',
            name='custom_domain_active',
            field=models.BooleanField(default=False),
        ),
    ]
