# Generated by Django 4.2.10 on 2026-02-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_automation', '0005_digitalcardentry_custom_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalcardentry',
            name='template_style',
            field=models.CharField(blank=True, default='design1', max_length=20),
        ),
    ]
