# Generated by Django 4.2.10 on 2026-03-06 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_automation', '0014_digitalcardentry_theme_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogueproduct',
            name='call_button_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='catalogueproduct',
            name='enquiry_button_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='catalogueproduct',
            name='whatsapp_button_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
