# Generated by Django 4.2.10 on 2026-03-07 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
        ("whatsapp_automation", "0015_catalogueproduct_call_button_enabled_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketingCampaign",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=180)),
                ("template_name", models.CharField(max_length=180)),
                ("template_variables", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("partial", "Partial"),
                            ("blocked", "Blocked"),
                            ("failed", "Failed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("total_contacts", models.PositiveIntegerField(default=0)),
                ("sent_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                ("skipped_count", models.PositiveIntegerField(default=0)),
                ("compliance_note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wa_marketing_campaigns_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wa_marketing_campaigns",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
                "indexes": [
                    models.Index(fields=["organization", "status"], name="whatsapp_aut_organiz_456cb0_idx"),
                    models.Index(fields=["organization", "created_at"], name="whatsapp_aut_organiz_3e1ea3_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="MarketingContact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, default="", max_length=160)),
                ("phone_number", models.CharField(max_length=40)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("tags", models.CharField(blank=True, default="", max_length=240)),
                ("is_opted_in", models.BooleanField(default=False)),
                ("opt_in_source", models.CharField(blank=True, default="", max_length=120)),
                ("consent_note", models.TextField(blank=True, default="")),
                ("has_opted_out", models.BooleanField(default=False)),
                ("opt_out_reason", models.CharField(blank=True, default="", max_length=160)),
                ("opt_in_at", models.DateTimeField(blank=True, null=True)),
                ("opted_out_at", models.DateTimeField(blank=True, null=True)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wa_marketing_contacts",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at", "-id"),
                "indexes": [
                    models.Index(fields=["organization", "phone_number"], name="whatsapp_aut_organiz_cf8f0a_idx"),
                    models.Index(
                        fields=["organization", "is_opted_in", "has_opted_out"],
                        name="whatsapp_aut_organiz_b94e10_idx",
                    ),
                ],
                "unique_together": {("organization", "phone_number")},
            },
        ),
        migrations.CreateModel(
            name="MarketingCampaignDelivery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("phone_number", models.CharField(max_length=40)),
                ("status", models.CharField(choices=[("sent", "Sent"), ("failed", "Failed"), ("skipped", "Skipped")], max_length=20)),
                ("error_code", models.CharField(blank=True, default="", max_length=120)),
                ("error_message", models.TextField(blank=True, default="")),
                ("attempted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="whatsapp_automation.marketingcampaign",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaign_deliveries",
                        to="whatsapp_automation.marketingcontact",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wa_marketing_deliveries",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("-attempted_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["organization", "status", "attempted_at"],
                        name="whatsapp_aut_organiz_503fc3_idx",
                    ),
                    models.Index(fields=["campaign", "status"], name="whatsapp_aut_campaig_44fb72_idx"),
                ],
            },
        ),
    ]
