# Generated by Django 4.2.10 on 2026-03-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_automation', '0016_marketing_campaign_and_contacts'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='marketingcampaign',
            new_name='whatsapp_au_organiz_29b007_idx',
            old_name='whatsapp_aut_organiz_456cb0_idx',
        ),
        migrations.RenameIndex(
            model_name='marketingcampaign',
            new_name='whatsapp_au_organiz_2e0230_idx',
            old_name='whatsapp_aut_organiz_3e1ea3_idx',
        ),
        migrations.RenameIndex(
            model_name='marketingcampaigndelivery',
            new_name='whatsapp_au_organiz_edb522_idx',
            old_name='whatsapp_aut_organiz_503fc3_idx',
        ),
        migrations.RenameIndex(
            model_name='marketingcampaigndelivery',
            new_name='whatsapp_au_campaig_bdf0e4_idx',
            old_name='whatsapp_aut_campaig_44fb72_idx',
        ),
        migrations.RenameIndex(
            model_name='marketingcontact',
            new_name='whatsapp_au_organiz_76645f_idx',
            old_name='whatsapp_aut_organiz_cf8f0a_idx',
        ),
        migrations.RenameIndex(
            model_name='marketingcontact',
            new_name='whatsapp_au_organiz_755728_idx',
            old_name='whatsapp_aut_organiz_b94e10_idx',
        ),
        migrations.AddField(
            model_name='cataloguepage',
            name='gallery_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cataloguepage',
            name='gallery_title',
            field=models.CharField(blank=True, default='Gallery', max_length=120),
        ),
    ]
