# Generated by Django 4.2.10 on 2026-03-09 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_automation', '0020_digitalcardfeedback_digitalcardenquiry'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='digitalcardenquiry',
            new_name='whatsapp_au_organiz_837d03_idx',
            old_name='whatsapp_au_organiz_01599e_idx',
        ),
        migrations.RenameIndex(
            model_name='digitalcardenquiry',
            new_name='whatsapp_au_organiz_c0495a_idx',
            old_name='whatsapp_au_organiz_107aa9_idx',
        ),
        migrations.RenameIndex(
            model_name='digitalcardenquiry',
            new_name='whatsapp_au_public__eba689_idx',
            old_name='whatsapp_au_public__9298e4_idx',
        ),
        migrations.RenameIndex(
            model_name='digitalcardfeedback',
            new_name='whatsapp_au_organiz_0409fa_idx',
            old_name='whatsapp_au_organiz_413e7c_idx',
        ),
        migrations.RenameIndex(
            model_name='digitalcardfeedback',
            new_name='whatsapp_au_organiz_187a40_idx',
            old_name='whatsapp_au_organiz_62f543_idx',
        ),
        migrations.RenameIndex(
            model_name='digitalcardfeedback',
            new_name='whatsapp_au_public__ba2904_idx',
            old_name='whatsapp_au_public__89c6cd_idx',
        ),
        migrations.RenameIndex(
            model_name='digitalcardvisit',
            new_name='whatsapp_au_organiz_4a08f2_idx',
            old_name='whatsapp_au_organiz_2306ea_idx',
        ),
        migrations.RenameIndex(
            model_name='digitalcardvisit',
            new_name='whatsapp_au_organiz_73b5de_idx',
            old_name='whatsapp_au_organiz_120fda_idx',
        ),
        migrations.RenameIndex(
            model_name='digitalcardvisit',
            new_name='whatsapp_au_card_en_6f377d_idx',
            old_name='whatsapp_au_card_en_e1b097_idx',
        ),
    ]
