# Generated by Django 4.2.10 on 2026-03-10 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_automation', '0021_rename_whatsapp_au_organiz_01599e_idx_whatsapp_au_organiz_837d03_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalcardentry',
            name='seo_description',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='digitalcardentry',
            name='seo_title',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
