# Generated by Django 4.2.10 on 2026-03-10 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_automation', '0022_digitalcardentry_seo_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalcardentry',
            name='save_contact_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
