# Generated by Django 4.2.10 on 2026-01-31 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0093_alter_pendingtransfer_receipt_upload_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageOrganizationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storage_settings', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='StorageFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_folders_created', to=settings.AUTH_USER_MODEL)),
                ('is_deleted', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_folders', to='core.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_folders', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='storage.storagefolder')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='StorageFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('storage_key', models.TextField()),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='storage.storagefolder')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_files', to='core.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StorageUserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_user_settings', to='core.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('organization', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='storagefolder',
            index=models.Index(fields=['organization', 'owner'], name='storage_sto_organiz_a30633_idx'),
        ),
        migrations.AddIndex(
            model_name='storagefolder',
            index=models.Index(fields=['organization', 'parent'], name='storage_sto_organiz_8c4538_idx'),
        ),
        migrations.AddIndex(
            model_name='storagefolder',
            index=models.Index(fields=['organization', 'owner', 'parent'], name='storage_sto_organiz_1c4c20_idx'),
        ),
        migrations.AddIndex(
            model_name='storagefile',
            index=models.Index(fields=['organization', 'owner'], name='storage_sto_organiz_12ab80_idx'),
        ),
        migrations.AddIndex(
            model_name='storagefile',
            index=models.Index(fields=['organization', 'folder'], name='storage_sto_organiz_a94251_idx'),
        ),
        migrations.AddIndex(
            model_name='storagefile',
            index=models.Index(fields=['organization', 'is_deleted'], name='storage_sto_organiz_3a2f7d_idx'),
        ),
    ]
