# Generated by Django 4.2.10 on 2026-01-31

from django.db import migrations


def seed_storage_backbone(apps, schema_editor):
    Product = apps.get_model("storage", "Product")
    Plan = apps.get_model("storage", "Plan")
    AddOn = apps.get_model("storage", "AddOn")

    product, _ = Product.objects.get_or_create(
        name="Online Storage",
        defaults={
            "is_active": True,
            "description": "Secure online cloud file storage with org-based controls.",
        },
    )
    if not product.is_active:
        product.is_active = True
        product.save(update_fields=["is_active"])

    plans = [
        {"name": "Basic", "max_users": 5, "storage_limit_gb": 250},
        {"name": "Standard", "max_users": 10, "storage_limit_gb": 500},
        {"name": "Pro", "max_users": None, "storage_limit_gb": 1024},
    ]
    for entry in plans:
        Plan.objects.get_or_create(
            product=product,
            name=entry["name"],
            defaults={
                "monthly_price": 0,
                "max_users": entry["max_users"],
                "storage_limit_gb": entry["storage_limit_gb"],
                "is_active": True,
            },
        )

    AddOn.objects.get_or_create(
        product=product,
        name="Extra Storage Slot",
        defaults={
            "storage_gb": 250,
            "price_monthly": 0,
            "stackable": True,
            "is_active": True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0003_product_plan_addon_orgsubscription_orgaddon"),
    ]

    operations = [
        migrations.RunPython(seed_storage_backbone, migrations.RunPython.noop),
    ]
