# Generated by Django 4.2.10 on 2026-01-31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0008_storage_index_rename"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrgStorageUsage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("used_storage_bytes", models.BigIntegerField(default=0)),
                ("last_calculated_at", models.DateTimeField(auto_now=True)),
                ("organization", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="storage_usage", to="core.organization")),
            ],
        ),
    ]
