# Generated by Django 4.2.10 on 2026-01-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0009_org_storage_usage"),
    ]

    operations = [
        migrations.AddField(
            model_name="storageglobalsettings",
            name="uploads_globally_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="storageglobalsettings",
            name="read_only_globally_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
