# Generated by Django 4.2.10 on 2026-02-05

from django.db import migrations, models


def backfill_device_limits(apps, schema_editor):
    Plan = apps.get_model("storage", "Plan")
    for plan in Plan.objects.all():
        name = (plan.name or "").strip().lower()
        if "basic" in name:
            limit = 2
        elif "standard" in name:
            limit = 3
        elif "pro" in name:
            limit = 5
        elif "trial" in name or "free" in name:
            limit = 1
        else:
            limit = 1
        if plan.device_limit != limit:
            plan.device_limit = limit
            plan.save(update_fields=["device_limit"])


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0013_add_bandwidth_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="device_limit",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.RunPython(backfill_device_limits, migrations.RunPython.noop),
    ]
