# Generated by Django 4.2.10 on 2026-02-05

from django.db import migrations


def backfill_device_limits(apps, schema_editor):
    Plan = apps.get_model("storage", "Plan")
    for plan in Plan.objects.all():
        name = (plan.name or "").strip().lower()
        if "basic" in name:
            limit = 2
        elif "standard" in name:
            limit = 3
        elif "pro" in name:
            limit = 5
        elif "trial" in name or "free" in name:
            limit = 1
        else:
            limit = 1
        if not plan.device_limit_per_user or plan.device_limit_per_user != limit:
            plan.device_limit_per_user = limit
            plan.save(update_fields=["device_limit_per_user"])


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0014_device_limit"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plan",
            old_name="device_limit",
            new_name="device_limit_per_user",
        ),
        migrations.RunPython(backfill_device_limits, migrations.RunPython.noop),
    ]
