# Generated by Django 4.2.10 on 2026-02-05

from django.db import migrations, models


def seed_storage_pricing(apps, schema_editor):
    Plan = apps.get_model("storage", "Plan")
    price_map = {
        "free": {"inr_m": 0, "inr_y": 0, "usd_m": 0, "usd_y": 0},
        "free trial": {"inr_m": 0, "inr_y": 0, "usd_m": 0, "usd_y": 0},
        "basic": {"inr_m": 999, "inr_y": 9999, "usd_m": 15, "usd_y": 150},
        "standard": {"inr_m": 1799, "inr_y": 17999, "usd_m": 29, "usd_y": 290},
        "pro": {"inr_m": 3499, "inr_y": 34999, "usd_m": 59, "usd_y": 590},
    }
    for plan in Plan.objects.all():
        key = (plan.name or "").strip().lower()
        if key not in price_map:
            continue
        values = price_map[key]
        plan.monthly_price_inr = values["inr_m"]
        plan.yearly_price_inr = values["inr_y"]
        plan.monthly_price_usd = values["usd_m"]
        plan.yearly_price_usd = values["usd_y"]
        plan.monthly_price = values["inr_m"]
        plan.yearly_price = values["inr_y"]
        plan.usd_monthly_price = values["usd_m"]
        plan.usd_yearly_price = values["usd_y"]
        plan.save(update_fields=[
            "monthly_price_inr",
            "yearly_price_inr",
            "monthly_price_usd",
            "yearly_price_usd",
            "monthly_price",
            "yearly_price",
            "usd_monthly_price",
            "usd_yearly_price",
        ])


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0015_rename_device_limit_per_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="monthly_price_inr",
            field=models.DecimalField(max_digits=12, decimal_places=2, default=0),
        ),
        migrations.AddField(
            model_name="plan",
            name="yearly_price_inr",
            field=models.DecimalField(max_digits=12, decimal_places=2, default=0),
        ),
        migrations.AddField(
            model_name="plan",
            name="monthly_price_usd",
            field=models.DecimalField(max_digits=12, decimal_places=2, default=0),
        ),
        migrations.AddField(
            model_name="plan",
            name="yearly_price_usd",
            field=models.DecimalField(max_digits=12, decimal_places=2, default=0),
        ),
        migrations.RunPython(seed_storage_pricing, migrations.RunPython.noop),
    ]
