# Generated by Django 4.2.10 on 2026-02-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0016_storage_plan_pricing_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgbandwidthusage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
