# Generated by Django 4.2.10 on 2026-03-25 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0018_update_free_device_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagefile',
            name='original_filename',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='storagefile',
            name='storage_key',
            field=models.TextField(default=''),
        ),
    ]
