# Generated by Django 6.0 on 2026-01-10

from django.db import migrations


def seed_products(apps, schema_editor):
    Product = apps.get_model("products", "Product")
    Product.objects.get_or_create(
        slug="monitor",
        defaults={
            "name": "Monitor",
            "short_description": "Work Zilla Monitoring and Productivity Insights.",
            "is_active": True,
            "sort_order": 1,
        },
    )


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_products, migrations.RunPython.noop),
    ]
