# Generated by Django 6.0 on 2026-01-11

from django.db import migrations


def seed_products(apps, schema_editor):
    Product = apps.get_model("products", "Product")
    Product.objects.get_or_create(
        slug="ai-chat-widget",
        defaults={
            "name": "AI Chat Widget",
            "short_description": "AI chat automation for support and lead capture.",
            "is_active": True,
            "sort_order": 2,
        },
    )
    Product.objects.get_or_create(
        slug="digital-card",
        defaults={
            "name": "Digital Card",
            "short_description": "Modern digital visiting cards for teams and sales.",
            "is_active": True,
            "sort_order": 3,
        },
    )


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_seed_initial_products"),
    ]

    operations = [
        migrations.RunPython(seed_products, migrations.RunPython.noop),
    ]
