# Generated by Django 6.0 on 2026-01-31

from django.db import migrations


def seed_storage_product(apps, schema_editor):
    Product = apps.get_model("products", "Product")
    Product.objects.get_or_create(
        slug="storage",
        defaults={
            "name": "Work Zilla Storage",
            "short_description": "Secure online cloud file storage with fast access and organization-based controls.",
            "is_active": True,
            "sort_order": 4,
        },
    )


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_seed_ai_chatbot"),
    ]

    operations = [
        migrations.RunPython(seed_storage_product, migrations.RunPython.noop),
    ]
