# Generated by Django 4.2.10 on 2026-01-31

from django.db import migrations


def update_storage_name(apps, schema_editor):
    Product = apps.get_model("products", "Product")
    Product.objects.filter(slug="storage").update(
        name="Online Storage",
        short_description="Secure online cloud file storage with fast access and organization-based controls.",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_seed_storage"),
    ]

    operations = [
        migrations.RunPython(update_storage_name, migrations.RunPython.noop),
    ]
