# Generated by Django 4.2.10 on 2026-04-28 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiArchitectSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='openai', max_length=40)),
                ('enabled', models.BooleanField(default=False)),
                ('model_name', models.CharField(default='gpt-4o-mini', max_length=120)),
                ('max_tokens', models.PositiveIntegerField(default=900)),
                ('allowed_scopes', models.JSONField(blank=True, default=dict)),
                ('encrypted_api_key', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Architect Settings',
                'verbose_name_plural': 'AI Architect Settings',
            },
        ),
        migrations.CreateModel(
            name='AiArchitectChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_architect_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='ai_architec_user_id_0603de_idx'), models.Index(fields=['session_id', 'created_at'], name='ai_architec_session_58ff9f_idx')],
            },
        ),
    ]
