# Generated by Django 4.2.10 on 2026-04-28 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_architect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiarchitectsettings',
            name='allow_error_logs_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aiarchitectsettings',
            name='hard_stop_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aiarchitectsettings',
            name='monthly_budget_inr',
            field=models.PositiveIntegerField(default=5000),
        ),
        migrations.AddField(
            model_name='aiarchitectsettings',
            name='response_mode',
            field=models.CharField(default='standard', max_length=40),
        ),
        migrations.AddField(
            model_name='aiarchitectsettings',
            name='warning_threshold_percent',
            field=models.PositiveIntegerField(default=80),
        ),
        migrations.CreateModel(
            name='AiArchitectUsageEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('cost_inr', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_architect_usage_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='ai_architec_user_id_19082d_idx'), models.Index(fields=['created_at'], name='ai_architec_created_091619_idx')],
            },
        ),
    ]
