# Generated by Django 4.2.10 on 2026-05-12 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_architect", "0002_aiarchitectsettings_allow_error_logs_read_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiarchitectsettings",
            name="openai_organization_id",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="aiarchitectsettings",
            name="openai_project_id",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
    ]

