# Generated by Django 6.0 on 2026-01-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_invoicesellerprofile_bank_account_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='active', max_length=20),
        ),
    ]
