# Generated by Django 6.0 on 2026-01-12 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auth_user_compat'),
        ('core', '0044_subscription_reminder_timestamp'),
    ]

    operations = [
    ]
