# Generated by Django 6.0 on 2026-01-12 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_merge_20260112_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingprofile',
            name='organization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.organization'),
        ),
    ]
