# Generated by Django 6.0 on 2026-01-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_billingprofile_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='org_company_key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='org_display_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pendingtransfer',
            name='org_company_key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pendingtransfer',
            name='org_display_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='subscriptionhistory',
            name='org_company_key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='subscriptionhistory',
            name='org_display_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
