# Generated by Django 6.0 on 2026-01-23 04:53

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_organization_settings_org_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='agent_role',
            field=models.CharField(blank=True, choices=[('sales', 'Sales'), ('support', 'Support'), ('both', 'Both')], default='support', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='chatwidget',
            name='public_chat_code',
            field=models.CharField(default=core.models._generate_chat_code, max_length=32, unique=True),
        ),
    ]
