# Generated by Django 6.0 on 2026-01-24 13:21

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_organization_settings_chatbot_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chattransferlog',
            new_name='core_chattr_organiz_996c59_idx',
            old_name='core_chattr_organiz_8b9c12_idx',
        ),
        migrations.RenameIndex(
            model_name='chattransferlog',
            new_name='core_chattr_convers_3658e6_idx',
            old_name='core_chattr_convers_4c91d3_idx',
        ),
        migrations.AlterField(
            model_name='chatwidget',
            name='public_chat_code',
            field=models.CharField(default=core.models._generate_chat_code, max_length=32, unique=True),
        ),
    ]
