# Generated by Django 6.0 on 2026-01-24 13:47

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_rename_core_chattr_organiz_8b9c12_idx_core_chattr_organiz_996c59_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatwidget',
            name='public_chat_code',
            field=models.CharField(default=core.models._generate_chat_code, max_length=32, unique=True),
        ),
    ]
