# Generated by Django 6.0 on 2026-01-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_aifaq'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='ai_library_limit_mb',
            field=models.PositiveIntegerField(blank=True, help_text='AI library storage limit in MB. Leave empty for unlimited.', null=True),
        ),
    ]
