# Generated by Django 6.0 on 2026-01-25 08:36

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_plan_website_page_limit'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aifaq',
            new_name='core_aifaq_organiz_b33f7a_idx',
            old_name='core_aifaq_organiz_2d4d8b_idx',
        ),
        migrations.AlterField(
            model_name='chatwidget',
            name='public_chat_code',
            field=models.CharField(default=core.models._generate_chat_code, max_length=32, unique=True),
        ),
    ]
