# Generated by Django 6.0 on 2026-01-25 08:59

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_rename_core_aifaq_organiz_2d4d8b_idx_core_aifaq_organiz_b33f7a_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatwidget',
            name='public_chat_code',
            field=models.CharField(default=core.models._generate_chat_code, max_length=32, unique=True),
        ),
    ]
