# Generated by Django 6.0 on 2026-01-28 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_unique_org_website_data'),
        ('core', '0087_alter_chatwidget_public_chat_code'),
    ]

    operations = [
    ]
