# Generated by Django 4.2.10 on 2026-01-31

from django.db import migrations


def seed_storage_plans(apps, schema_editor):
    Product = apps.get_model("products", "Product")
    Plan = apps.get_model("core", "Plan")
    product = Product.objects.filter(slug="storage").first()
    if not product:
        return

    plans = [
        {
            "name": "Basic",
            "limits": {"storage_gb": 250, "max_users": 5},
            "sort_key": 1,
        },
        {
            "name": "Standard",
            "limits": {"storage_gb": 500, "max_users": 10},
            "sort_key": 2,
        },
        {
            "name": "Pro",
            "limits": {"storage_gb": 1024, "max_users": 0},
            "sort_key": 3,
        },
    ]

    for entry in plans:
        plan, _ = Plan.objects.get_or_create(
            product=product,
            name=entry["name"],
            defaults={
                "price": 0,
                "monthly_price": 0,
                "yearly_price": 0,
                "usd_monthly_price": 0,
                "usd_yearly_price": 0,
                "addon_monthly_price": 0,
                "addon_yearly_price": 0,
                "addon_usd_monthly_price": 0,
                "addon_usd_yearly_price": 0,
                "employee_limit": 0,
                "duration_months": 1,
                "retention_days": 30,
                "allow_addons": True,
                "limits": entry["limits"],
                "addons": {"extra_storage_slot_gb": 250, "extra_storage_slot_name": "Extra Storage Slot"},
                "features": {},
            },
        )
        if plan:
            limits = plan.limits or {}
            limits.update(entry["limits"])
            plan.limits = limits
            plan.allow_addons = True
            plan.employee_limit = 0
            addons = plan.addons or {}
            addons.setdefault("extra_storage_slot_gb", 250)
            addons.setdefault("extra_storage_slot_name", "Extra Storage Slot")
            plan.addons = addons
            plan.save(update_fields=["limits", "allow_addons", "employee_limit", "addons"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0093_alter_pendingtransfer_receipt_upload_to"),
        ("products", "0005_seed_storage"),
    ]

    operations = [
        migrations.RunPython(seed_storage_plans, migrations.RunPython.noop),
    ]
