# Generated by Django 4.2.10 on 2026-02-05 07:58

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_device_model_and_limit'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='device',
            new_name='core_device_org_id_e4b0ac_idx',
            old_name='core_device_org_use_b0db7b_idx',
        ),
        migrations.RenameIndex(
            model_name='device',
            new_name='core_device_user_id_be6154_idx',
            old_name='core_device_user_id_8d02b4_idx',
        ),
        migrations.AlterField(
            model_name='chatwidget',
            name='public_chat_code',
            field=models.CharField(default=core.models._generate_chat_code, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('company_admin', 'Company Admin'), ('org_user', 'Org User'), ('hr_view', 'HR View'), ('ai_chatbot_agent', 'AI Chatbot Agent'), ('dealer', 'Dealer')], default='company_admin', max_length=20),
        ),
    ]
